name: Docker

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    # - name: 'Print GH event data'
    #  env:
    #    EVENT_CONTEXT: ${{ toJSON(github.event) }}
    #  run: |
    #    echo $EVENT_CONTEXT
    - name: 'Checkout with full history'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: 'Get last git tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
    - env:
        LAST_TAG: ${{ steps.previoustag.outputs.tag }}
      run: |
        echo $LAST_TAG
        echo "LAST_TAG=$LAST_TAG" >> $GITHUB_ENV      
    - name: 'Set up JDK 17'
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: 'Download jar for last tag'
      run: |
        mvn -B dependency:copy -Dartifact=com.example:webapp:${{ env.LAST_TAG }} -DoutputDirectory=target
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Build docker image and push
      uses: docker/build-push-action@v3
      with:
        context: .
        build-args: APP_VERSION=${{ env.LAST_TAG }}
        platforms: linux/amd64
        push: true
        tags: |
            ghcr.io/edipal/genie-website-java:${{ env.LAST_TAG }}
 
