name: Docker

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - env:
        EVENT_CONTEXT: ${{ toJSON(github.event) }}
      run: |
        echo $EVENT_CONTEXT
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
    - env:
        LAST_TAG: ${{ steps.previoustag.outputs.tag }}
      run: |
        echo $LAST_TAG    
    
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag genie-website-java:$(date +%s)
