name: Docker

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - env:
        EVENT_CONTEXT: ${{ toJSON(github.event) }}
      run: |
        echo $EVENT_CONTEXT
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
    - env:
        LAST_TAG: ${{ steps.previoustag.outputs.tag }}
      run: |
        echo $LAST_TAG
        echo "LAST_TAG=$LAST_TAG" >> $GITHUB_ENV      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: 'Download last released jar'
      run: |
        mvn -B dependency:copy -Dartifact=com.example:webapp:${{ env.LAST_TAG }} -DoutputDirectory=target -DrepositoryId=github --global-settings settings.xml
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/edipal/genie-website-java:${{ env.LAST_TAG }} --build-arg APP_VERSION=${{ env.LAST_TAG }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
            ghcr.io/edipal/genie-website-java:${{ env.LAST_TAG }}
 
