name: Release

on:
  workflow_dispatch:
jobs:
  maven-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.GH_SSH_KEY }}
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Release
      run: mvn -B release:prepare release:perform
