name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: 'Checkout'
      uses: actions/checkout@v4.1.1

    - name: 'Install SSH key'
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.GH_SSH_KEY }}
        name: id_ed25519
        known_hosts: ${{ secrets.GH_KNOWN_HOSTS }}
    
    # - name: 'Debug ssh connection'
    #   run: |
    #     ssh -vT git@github.com
    
    - name: 'Configure git user'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    
    - name: 'Set up JDK 17'
      uses: actions/setup-java@v4.0.0
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: 'Maven release'
      run: mvn -B release:prepare release:perform -DtagNameFormat=@{project.version}
      env:
        GITHUB_TOKEN: ${{ github.token }}
